name: 'Terraform Deployment'

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

permissions:
  contents: read

jobs:
  terraform-prod:
    name: 'Terraform Deployment - Production'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # ✅ Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # ✅ Setup AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    # ✅ Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3 # Update if you have a specific version

    # ✅ Terraform Initialization
    - name: Terraform Init
      run: terraform init -input=false

    # ✅ Validate Terraform Files
    - name: Terraform Validate
      run: terraform validate

    # # ✅ Check Terraform Format
    # - name: Terraform Format
    #   run: terraform fmt -check

    # ✅ Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    # ✅ Terraform Apply (Only on Main Branch Push)
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan


  terraform-pre-prod:
    name: 'Terraform Deployment - Pre-Production'
    runs-on: ubuntu-latest
    environment: pre-prod

    defaults:
      run:
        shell: bash

    steps:
    # ✅ Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # ✅ Setup AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    # ✅ Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3 # Update if you have a specific version

    # ✅ Terraform Initialization
    - name: Terraform Init
      run: terraform init -input=false

    # ✅ Validate Terraform Files
    - name: Terraform Validate
      run: terraform validate

    # # ✅ Check Terraform Format
    # - name: Terraform Format
    #   run: terraform fmt -check

    # ✅ Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    # ✅ Terraform Apply (Only on Main Branch Push)
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
