name: 'Terraform Deployment'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-prod:
    name: 'Terraform Deployment - Production'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        ECR_REPOSITORY: my-repo-${{ github.ref_name }}
      run: terraform plan -input=false -out=tfplan -var="environment=production" -var="repository_name=${{ env.ECR_REPOSITORY }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan

  terraform-pre-prod:
    name: 'Terraform Deployment - Pre-Production'
    runs-on: ubuntu-latest
    environment: pre-prod

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Validate
      run: terraform validate

    - name : Terraform Plan
      env:
        ECR_REPOSITORY: my-repo-${{ github.ref_name }}
      run: terraform plan -input=false -out=tfplan -var="environment=pre-prod" -var="repository_name=${{ env.ECR_REPOSITORY }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan